#!/usr/bin/env bash
# Create the host-only control-plane environment.  This script never starts Docker.
set -euo pipefail

readonly SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
readonly ENV_FILE="$SCRIPT_DIR/hetzner.env"
readonly TENANT_PUBLIC_ENV="$SCRIPT_DIR/tenant-provisioning.env"
readonly STATE_PARENT=/srv/auto-browser-public
readonly IDENTITY_STATE="$STATE_PARENT/identity"
readonly PORTAL_STATE="$STATE_PARENT/portal"
readonly GATEWAY_STATE="$STATE_PARENT/mcp-gateway"
readonly TENANT_STATE=/srv/auto-browser-tenants

if [[ ${EUID} -ne 0 ]]; then
  echo 'Run as root so the environment is owned by root.' >&2
  exit 1
fi

rotate=false
case "${1:-}" in
  '') ;;
  --rotate) rotate=true ;;
  *) echo 'Usage: bootstrap.sh [--rotate]' >&2; exit 2 ;;
esac

if [[ ( -e "$ENV_FILE" || -e "$TENANT_PUBLIC_ENV" ) && "$rotate" != true ]]; then
  echo 'Refusing to replace existing host environment; use --rotate explicitly.' >&2
  exit 1
fi

# The three images run as UID 10001.  Tenant descriptors carry broker
# credentials that portal and gateway must read and update, so the registry is
# deliberately private to that service UID rather than root-owned 0600 files.
install -d -o root -g root -m 0711 "$STATE_PARENT"
for directory in "$IDENTITY_STATE" "$PORTAL_STATE" "$GATEWAY_STATE" "$TENANT_STATE"; do
  if [[ -e "$directory" ]]; then
    [[ -d "$directory" && ! -L "$directory" ]] || {
      echo "Refusing unsafe state path: $directory" >&2; exit 1;
    }
    [[ $(stat -c '%u:%g:%a' "$directory") == 10001:10001:700 ]] || {
      echo "Existing state path has unsafe ownership or mode: $directory" >&2; exit 1;
    }
  else
    # `install -o` requires a resolvable account name; the service UID is
    # deliberately not a host user, so create then chown numerically.
    mkdir -p -- "$directory"
    chmod 0700 -- "$directory"
    chown 10001:10001 -- "$directory"
  fi
done

umask 077
tmp_env="$(mktemp "$SCRIPT_DIR/.hetzner.env.XXXXXX")"
tmp_tenant_env="$(mktemp "$SCRIPT_DIR/.tenant-provisioning.env.XXXXXX")"
tmp_key="$(mktemp "$SCRIPT_DIR/.portal-key.XXXXXX")"
tmp_pub="$(mktemp "$SCRIPT_DIR/.portal-pub.XXXXXX")"
cleanup() { rm -f -- "$tmp_env" "$tmp_tenant_env" "$tmp_key" "$tmp_pub"; }
trap cleanup EXIT HUP INT TERM

token() {
  head -c 48 /dev/urandom | base64 -w 0 | tr '+/' '-_' | tr -d '='
}

# OpenSSL emits standard ASN.1 wrappers for Ed25519 keys; their final 32 bytes
# are the raw key material required by portal.py and approval_broker.py.
openssl genpkey -algorithm ED25519 -out "$tmp_key" >/dev/null 2>&1
private_key="$(openssl pkey -in "$tmp_key" -outform DER 2>/dev/null | tail -c 32 | base64 -w 0 | tr '+/' '-_' | tr -d '=')"
openssl pkey -in "$tmp_key" -pubout -outform DER -out "$tmp_pub" >/dev/null 2>&1
public_key="$(tail -c 32 "$tmp_pub" | base64 -w 0 | tr '+/' '-_' | tr -d '=')"

if [[ ${#private_key} -ne 43 || ${#public_key} -ne 43 ]]; then
  echo 'Ed25519 key generation failed.' >&2
  exit 1
fi

cat >"$tmp_env" <<EOF
# Root-owned host configuration. Generated by bootstrap.sh; never commit or print.
PORTAL_PUBLIC_ORIGIN=https://secure-browser.fareeqk.com
MCP_GATEWAY_ISSUER_URL=https://mcp-browser.fareeqk.com
MCP_GATEWAY_RESOURCE_URL=https://mcp-browser.fareeqk.com/mcp
MCP_GATEWAY_PORTAL_URL=https://secure-browser.fareeqk.com
IDENTITY_HOST_STATE_ROOT=$IDENTITY_STATE
PORTAL_HOST_STATE_ROOT=$PORTAL_STATE
MCP_GATEWAY_HOST_STATE_ROOT=$GATEWAY_STATE
TENANT_STACK_HOST_ROOT=$TENANT_STATE
TENANT_CONTROL_NETWORK=auto-browser-tenant-control
IDENTITY_TRUSTED_PROXY_CIDRS=127.0.0.1/32
PORTAL_AUTHENTICATION_FRESHNESS_SECONDS=120

IDENTITY_ADMIN_TOKEN=$(token)
IDENTITY_INTERNAL_TOKEN=$(token)
IDENTITY_ENCRYPTION_KEY=$(head -c 32 /dev/urandom | base64 -w 0)
IDENTITY_RECOVERY_PEPPER=$(token)
MCP_GATEWAY_INTERNAL_TOKEN=$(token)
TENANT_POLICY_INTERNAL_TOKEN=$(token)
PORTAL_ASSERTION_PRIVATE_KEY=$private_key
# This is intentionally public and is copied into each tenant's private env.
BROKER_PORTAL_ASSERTION_PUBLIC_KEY=$public_key
EOF

# This companion contains only the verification key needed by the trusted
# tenant provisioner.  It deliberately contains no portal signing material.
printf 'BROKER_PORTAL_ASSERTION_PUBLIC_KEY=%s\n' "$public_key" >"$tmp_tenant_env"

chown root:root "$tmp_env"
chmod 0600 "$tmp_env"
mv -f -- "$tmp_env" "$ENV_FILE"
chown root:root "$ENV_FILE"
chmod 0600 "$ENV_FILE"
chown root:root "$tmp_tenant_env"
chmod 0644 "$tmp_tenant_env"
mv -f -- "$tmp_tenant_env" "$TENANT_PUBLIC_ENV"
chown root:root "$TENANT_PUBLIC_ENV"
chmod 0644 "$TENANT_PUBLIC_ENV"

echo 'Created protected hetzner.env; credentials were not printed. Services were not started.'
